stages:
- name: publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: goorion/myapplication:latest
      pushRemote: true
      registry: hub.docker.com
- name: redeploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
