apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: myapp-dpl
spec:
 replicas: 3
 template:
   metadata:
     labels:
       name: myapp
   spec:
     containers:
     - name: myapp
       image: goorion/myapplication
       imagePullPolicy: Never
       ports:
       - containerPort: 5000